version: '3'

services:
    rabbitmq:
        image: rabbitmq:3-management
        hostname: 'localhost'
        environment:
            RABBITMQ_DEFAULT_USER: rabbitmq
            RABBITMQ_DEFAULT_PASS: rabbitmq
        ports:
            - '5672:5672'
            - '15672:15672'
        labels:
            NAME: rabbitmq
        volumes:
            - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    sql:
        image: postgres:latest
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - 6805:5432

volumes:
    db-data:
        driver: local
