version: '3'

services:
    queue:
        image: node:10-alpine
        volumes:
            - .:/app
        links:
            - rabbitmq
            - sql
        depends_on:
            - rabbitmq
            - sql
    rabbitmq:
        image: rabbitmq:3-management
        hostname: 'rabbitmq'
        environment:
            RABBITMQ_DEFAULT_USER: rabbitmq
            RABBITMQ_DEFAULT_PASS: rabbitmq
        ports:
            - '15672:15672'
        labels:
            NAME: rabbitmq
        volumes:
            - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    sql:
        image: postgres:latest
        volumes:
            - db-data:/var/lib/postgresql/data
            - .:/app
        ports:
            - 6805:5432

volumes:
    db-data:
        driver: local
